### ISSUE TITLE
Error messages are shown when a ddu source adds items while in cmdwin

### ISSUE THREAD

**Issue by mityu** [Shougo/ddu-ui-ff#130]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

Error messages (E11 error caught by denops.vim) are shown when a ddu source adds items while you're in cmdwin.

## Expected

No error is given.

## Environment Information

- ddu-ui-ff version (SHA1): `6a02ebfb4966fc602fca3c34c662fb76516a8858`

- denops.vim version (SHA1): `83f167b034e9e56913d8a89b026a6b0eb79b52b4`

- ddu version: `904558a8732da3614822157007b93aabd71838bd`

- ddu-source-file_rec version: `09ebb6274179e36e888fd2aba69edc96c8ab95b9` 

- deno version(`deno -V` output): `deno 1.39.4`

- OS: macOS Ventura

- neovim/Vim `:version` output:

```
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan 18 2024 03:52:10)
macOS version - arm64
Included patches: 1-35
Compiled by mityu
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term -gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3/dyn       +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
-cscope            +localmap          -ruby              +wildignore
+cursorbind        -lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      +sodium            -X11
+digraphs          +mouse             +sound             -xattr
-dnd               -mouseshape        +spell             -xfontset
-ebcdic            +mouse_dec         +startuptime       -xim
+emacs_tags        -mouse_gpm         +statusline        -xpm
+eval              -mouse_jsbterm     -sun_workshop      -xsmp
+ex_extra          +mouse_netterm     +syntax            -xterm_clipboard
+extra_search      +mouse_sgr         +tag_binary        -xterm_save
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/Users/mityu/.local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_DARWIN -O2 -Wall -Wno-deprecated-declarations -I/opt/homebrew/Cellar/libsodium/1.0.19/include -D_REENTRANT -I/opt/homebrew/Cellar/libsodium/1.0.19/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L/usr/local/lib -o vim -lm -lncurses -L/opt/homebrew/Cellar/libsodium/1.0.19/lib -lsodium -liconv -framework AppKit 
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
" Your minimal init.vim/vimrc
set nocompatible

set runtimepath^=~/.cache/vim/pack/minpac/opt/denops.vim
set runtimepath^=~/.cache/vim/pack/minpac/opt/ddu.vim
set runtimepath^=~/.cache/vim/pack/minpac/opt/ddu-ui-ff
set runtimepath^=~/.cache/vim/pack/minpac/opt/ddu-source-file_rec

let s:path = expand('~')  " Can be any directory that contains many files.

call ddu#custom#patch_global('ui', 'ff')
call ddu#custom#patch_global('sourceOptions', { 'file_rec': { 'path': s:path } })

autocmd Filetype ddu-ff nnoremap <buffer> <C-w>q <Cmd>call ddu#ui#do_action('quit')<CR>

nnoremap @ <Cmd>call ddu#start({'sources': [{'name': 'file_rec'}]})<CR>
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Open vim with `vim -u /path/to/vimrc`.
2. Type `@` to start ddu.
3. Type `q:` to open cmdwin.
4. Error messages are shown soon.  Close cmdwin and ddu window.
5. Check given error messages with `:mes`

## Upload the log messages by `:redir` and `:message` (if errored)

```
[ddu] ui: ff "redraw()" failed
[ddu] Failed to call 'win_gotoid(1002)': Vim(let):E11: Invalid in command-line window; :q<CR> closes the window^@function denops#api#vim#call, line 2
[ddu] Error: Failed to call 'win_gotoid(1002)': Vim(let):E11: Invalid in command-line window; :q<CR> closes the window^@function denops#api#vim#call, line 2^@    at Vim.call (file:///Users/mityu/.cache/vim/pack/minpac/opt/denops.vim/denops/@denops-private/host/vim.ts:64:13)^@    at eventLoopTick (ext:core/01_core.js:182:7)^@    at async dispatch (https://deno.land/x/messagepack_rpc@v2.0.3/dispatcher.ts:36:12)^@    at async Session.#dispatch (https://deno.land/x/messagepack_rpc@v2.0.3/session.ts:244:22)^@    at async Session.#handleRequestMessage (https://deno.land/x/messagepack_rpc@v2.0.3/session.ts:271:33)
```

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
Fixed.  Please update ddu.vim.

**Comment by mityu** [comment]
Thank you!
