### ISSUE TITLE
File pops up instead of opening ddu-ui

### ISSUE THREAD

**Issue by staticWagomU** [Shougo/ddu-ui-ff#153]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
When ddu with uiParams set to `floatingBorder: 'single' `is started with winbar set, ddu-ui is not opened in a popup but the previously opened buffer is opened in a popup and an error occurs.

## Expected

I want ddu-ui to open

## Environment Information

- ddu-ui-ff version (SHA1):[dd6cc89edd4d19996eaf3cb9247be2e4c58e83c9](https://github.com/Shougo/ddu-ui-ff/tree/dd6cc89edd4d19996eaf3cb9247be2e4c58e83c9)

- denops.vim version (SHA1):[45b8a1c45fe06e95538fc701ee7d6e3cc5335659](https://github.com/vim-denops/denops.vim/tree/45b8a1c45fe06e95538fc701ee7d6e3cc5335659)

- deno version(`deno -V` output):
```
$ deno -v
deno 1.45.4
```

- OS: WSL2
```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

- neovim/Vim `:version` output:
```
NVIM v0.11.0-dev-635+g1d11808bf
Build type: Debug
LuaJIT 2.1.1724081603
Run ":verbose version" for more info
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/tmp/denops.vim
set rtp+=~/tmp/ddu.vim
set rtp+=~/tmp/ddu-ui-ff
set rtp+=~/tmp/ddu-source-file_rec

call ddu#custom#patch_local('hoge', #{
      \ ui: 'ff',
      \ sources: [
      \  #{
      \    name: 'file_rec',
      \  },
      \ ],
      \ uiParams: #{
      \   ff: #{
      \    floatingTitle: 'Hoge',
      \    autoResize: v:true,
      \    split: 'floating',
      \    floatingBorder: 'single',
      \   },
      \ },
      \})


lua << EOF
vim.api.nvim_create_autocmd({ 'VimEnter', 'BufEnter', 'BufModifiedSet', 'WinEnter', 'WinLeave' }, {
  group = vim.api.nvim_create_augroup('Hoge', { clear = true }),
  pattern = '*',
  callback = function()
    for _, buf in ipairs(vim.fn.getbufinfo({ buflisted = 1 })) do
        local winid = vim.fn.bufwinid(buf.bufnr)
        if winid ~= -1 then
          vim.fn.setwinvar(winid, '&winbar', 'Fuga')
        end
    end
  end,
})
EOF


```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Open any file
2. Run `call call ddu#start(#{name:'hoge'})`

## Screenshot (if possible)

![image](https://github.com/user-attachments/assets/fcd5f201-b463-4973-b794-43a0a692e283)

## Upload the log messages by `:redir` and `:message` (if errored)
```
[ddu] ui: ff "redraw()" failed
[ddu] Error: Failed to call 'nvim_open_win' in Neovim: Vim:E5555: API call: WinLeave Autocommands for "*": Vim(append):Error executing lua callback: Vim:E36: Not enough ro
om
[ddu] stack traceback:
[ddu] ^I[C]: in function 'setwinvar'
[ddu] ^I[string ":lua"]:8: in function <[string ":lua"]:4> (code: 0)
[ddu]     at Neovim.call (file:///home/beige/tmp/denops.vim/denops/@denops-private/host/nvim.ts:68:15)
[ddu]     at eventLoopTick (ext:core/01_core.js:168:7)
[ddu]     at async Ui.redraw (file:///home/beige/tmp/ddu-ui-ff/denops/@ddu-uis/ff.ts:430:27)
[ddu]     at async file:///home/beige/tmp/ddu.vim/denops/ddu/ext.ts:942:7
[ddu]     at async Lock.lock (https://jsr.io/@lambdalisue/async/2.1.1/lock.ts:51:14)
[ddu]     at async uiRedraw (file:///home/beige/tmp/ddu.vim/denops/ddu/ext.ts:916:3)
[ddu]     at async Ddu.uiRedraw (file:///home/beige/tmp/ddu.vim/denops/ddu/ddu.ts:790:5)
[ddu]     at async Ddu.start (file:///home/beige/tmp/ddu.vim/denops/ddu/ddu.ts:239:5)
[ddu]     at async file:///home/beige/tmp/ddu.vim/denops/ddu/app.ts:252:9
[ddu]     at async Lock.lock (https://jsr.io/@lambdalisue/async/2.1.1/lock.ts:51:14)
[ddu] ui: ff "redraw()" failed
[ddu] Error: Failed to call 'nvim_open_win' in Neovim: Vim:E5555: API call: WinLeave Autocommands for "*": Vim(append):Error executing lua callback: Vim:E36: Not enough ro
om
[ddu] stack traceback:
[ddu] ^I[C]: in function 'setwinvar'
[ddu] ^I[string ":lua"]:8: in function <[string ":lua"]:4> (code: 0)
[ddu]     at Neovim.call (file:///home/beige/tmp/denops.vim/denops/@denops-private/host/nvim.ts:68:15)
[ddu]     at eventLoopTick (ext:core/01_core.js:168:7)
[ddu]     at async Ui.redraw (file:///home/beige/tmp/ddu-ui-ff/denops/@ddu-uis/ff.ts:430:27)
[ddu]     at async file:///home/beige/tmp/ddu.vim/denops/ddu/ext.ts:942:7
[ddu]     at async Lock.lock (https://jsr.io/@lambdalisue/async/2.1.1/lock.ts:51:14)
[ddu]     at async uiRedraw (file:///home/beige/tmp/ddu.vim/denops/ddu/ext.ts:916:3)
[ddu]     at async Ddu.uiRedraw (file:///home/beige/tmp/ddu.vim/denops/ddu/ddu.ts:790:5)
[ddu]     at async Ddu.#redrawInternal (file:///home/beige/tmp/ddu.vim/denops/ddu/ddu.ts:761:5)
[ddu]     at async file:///home/beige/tmp/ddu.vim/denops/ddu/ddu.ts:577:13
```

```

**Comment by Shougo** [comment]
Hm...  It seems feature.

You can test `setlocal winbar=Hoge` when empty floating window.

**Comment by Shougo** [comment]
It works for me.

```vim
lua << EOF
vim.api.nvim_create_autocmd({ 'VimEnter', 'BufEnter', 'BufModifiedSet', 'WinEnter', 'WinLeave' }, {
  group = vim.api.nvim_create_augroup('Hoge', { clear = true }),
  pattern = '*',
  callback = function()
    for _, buf in ipairs(vim.fn.getbufinfo({ buflisted = 1 })) do
        local winid = vim.fn.bufwinid(buf.bufnr)
        if winid ~= -1 and vim.fn.line('$', winid) > 1 then
          vim.fn.setwinvar(winid, '&winbar', 'Fuga')
        end
    end
  end,
})
vim.api.nvim_create_autocmd({ 'User' }, {
  group = vim.api.nvim_create_augroup('Hoge', { clear = true }),
  pattern = 'Ddu:uiDone',
  callback = function()
    if vim.fn.line('$') > 1 then
      vim.fn.setwinvar(vim.fn.win_getid(), '&winbar', 'Fuga')
    end
  end,
})
EOF
```
