### ISSUE TITLE
Since the 2nd opening of DDU list, there would be "Not allowed to change text or change window" error

### ISSUE THREAD

**Issue by mikelue** [Shougo/ddu-ui-ff#155]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

The first time of opening for DDU list, nothing get wrong. But the follow-up openings bring the error message.

If I use `bdelete` to delete DDU buffer of list, it would get back to 1st opening situation.

## Expected

No error message

## Environment Information

- ddu-ui-ff version (SHA1):
`6d8ebbfb9eb970f1a040879107be6e9b24ef7749`

- denops.vim version (SHA1):
` 3a38e081f922e0134671236edd3e6dcbb251d10c `

- deno version(`deno -V` output):
`deno 1.40.2`

- OS:
(`Ubuntu 24.04.1 LTS` on `5.15.153.1-microsoft-standard-WSL2`)

- neovim/Vim `:version` output:
```
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Nov  6 2024 11:27:23)
Included patches: 1-842
Compiled by mike@lt-mike
Huge version without GUI.  Features included (+) or not (-):
+acl               -browse            +cmdline_compl     +cursorbind        +emacs_tags        +float             +insert_expand     +libcall           +mksession         +mouse_netterm     -mzscheme          +popupwin          +reltime           -sound             -tag_old_static    +textobjects       +vertsplit         +wildignore        -xim
-arabic            ++builtin_terms    +cmdline_hist      +cursorshape       +eval              +folding           +ipv6              +linebreak         +modify_fname      +mouse_sgr         +netbeans_intg     +postscript        -rightleft         +spell             -tag_any_white     +textprop          +vim9script        +wildmenu          -xpm
+autocmd           +byte_offset       +cmdline_info      +dialog_con        +ex_extra          -footer            +job               +lispindent        +mouse             -mouse_sysmouse    +num64             +printer           -ruby              +startuptime       -tcl               +timers            +viminfo           +windows           +xsmp_interact
+autochdir         +channel           +comments          +diff              +extra_search      +fork()            +jumplist          +listcmds          -mouseshape        +mouse_urxvt       +packages          +profile           +scrollbind        +statusline        +termguicolors     +title             +virtualedit       +writebackup       +xterm_clipboard
-autoservername    +cindent           +conceal           +digraphs          -farsi             -gettext           +keymap            +localmap          +mouse_dec         +mouse_xterm       +path_extra        -python            +signs             -sun_workshop      +terminal          -toolbar           +visual            +X11               -xterm_save
-balloon_eval      +clientserver      +cryptv            -dnd               +file_in_path      -hangul_input      +lambda            +lua/dyn           -mouse_gpm         +multi_byte        +perl/dyn          +python3/dyn       +smartindent       +syntax            +terminfo          +user_commands     +visualextra       +xattr
+balloon_eval_term +clipboard         +cscope            -ebcdic            +find_in_path      +iconv             +langmap           +menu              -mouse_jsbterm     +multi_lang        +persistent_undo   +quickfix          -sodium            +tag_binary        +termresponse      +vartabs           +vreplace          +xfontset
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
 3rd user vimrc file: "$XDG_CONFIG_HOME/vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -g -O3 -Wall -march=alderlake -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -Wl,-E -L/usr/local/lib -Wl,--as-needed -o vim -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lrt
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)
[vimrc.minimal.zip](https://github.com/user-attachments/files/17644595/vimrc.minimal.zip)

## How to reproduce the problem from neovim/Vim startup (Required!)

1. run `:Ddu buffer`(by `ddu-commands`), then close it(by `call ddu#ui#sync_action('quit')`).
2. run `:Ddu buffer` again.
3. The error messages should be shown as following

## Upload the log messages by `:redir` and `:message` (if errored)
```
[ddu] BatchError: Failed to call 'ddu#ui#ff#_update_buffer' in Vim: Vim(delete):E565: Not allowed to change text or change window
[ddu] function <SNR>46_DduSourceName[4]..ddu#custom#get_current[1]..ddu#denops#_request[15]..denops#request[1]..denops#_internal#server#chan#request[6]..denops#_internal#rpc#vim#request[1]..denops#api#vim#batch[3]..<lambda>4858[1]..ddu#ui#ff#_update_buffer, line 17
[ddu]     at DenopsImpl.batch (file:///home/mike/.vim/plugged/denops.vim/denops/@denops-private/denops.ts:67:13)
[ddu]     at eventLoopTick (ext:core/01_core.js:63:7)
[ddu]     at async batch (https://jsr.io/@denops/std/7.3.0/batch/batch.ts:198:3)
[ddu]     at async Ui.redraw (file:///home/mike/.vim/plugged/ddu-ui-ff/denops/@ddu-uis/ff.ts:597:7)
[ddu]     at async file:///home/mike/.vim/plugged/ddu.vim/denops/ddu/ext.ts:950:7
[ddu]     at async Lock.lock (https://jsr.io/@core/asyncutil/1.2.0/lock.ts:48:14)
[ddu]     at async uiRedraw (file:///home/mike/.vim/plugged/ddu.vim/denops/ddu/ext.ts:924:3)
[ddu]     at async Ddu.uiRedraw (file:///home/mike/.vim/plugged/ddu.vim/denops/ddu/ddu.ts:793:5)
[ddu]     at async Ddu.start (file:///home/mike/.vim/plugged/ddu.vim/denops/ddu/ddu.ts:246:5)
[ddu]     at async file:///home/mike/.vim/plugged/ddu.vim/denops/ddu/app.ts:255:9
[ddu] [ddu-ui-ff] update buffer failed
```

**Comment by Shougo** [comment]
Sorry.  I can't help you.

Because you don't upload the minimal config.  ddu.vim does not work your configuration.
ddu.vim is not same with other plugins.  It `does not work` without any plugin config.

**Comment by Shougo** [comment]
Please see other issue like this.

https://github.com/Shougo/ddu-ui-ff/issues/154

I will close your issue if you don't upload the real minimal config.

> Open any DDU list, then close it(by ddu#ui#sync_action('quit')).
> Open any DDU list again.

It must be real command.

**Comment by Shougo** [comment]
I have read Vim's source code.  The message is from textlock state.
So I need to reproduce your problem.

**Comment by mikelue** [comment]
I've refined the information for the issue. Let me know if any information is still insufficient.
Thanks a lot.

**Comment by Shougo** [comment]
OK.  I will check your config later.

**Comment by Shougo** [comment]
I don't reproduce your behavior.

```vim
set mouse=a

set autoindent
set autoread
set autowrite

set cmdheight=1

set hlsearch

set modeline
set foldcolumn=2
set foldlevel=1
set foldminlines=3
set backspace=2

set smarttab
set tabstop=4
set shiftwidth=4
set noexpandtab
set fileformats=unix,dos

set previewheight=32

set splitright

set viminfo+=:128

set dictionary=~/vimfiles/dictionary/6of12.txt
set wildignore=*/*classes/*,*.class

set rtp+=~/work/denops.vim
set rtp+=~/work/ddu.vim
set rtp+=~/work/ddu-ui-ff
set rtp+=~/work/ddu-filter-matcher_substring
set rtp+=~/work/ddu-kind-file
set rtp+=~/work/ddu-commands.vim
set rtp+=~/work/ddu-source-file

set nobackup
set nowritebackup
set undofile

set signcolumn=auto

set cursorline

call ddu#custom#patch_global(#{
      \ ui: 'ff',
      \ uiParams: #{
      \ ff: #{
      \ prompt: "\ue62b ",
      \ previewSplit: 'vertical',
      \ previewWidth: 160,
      \ statusline: v:false,
      \ filterSplitDirection: "botright",
      \ maxDisplayItems: 512,
      \ maxHighlightItems: 128,
      \ }
      \ },
      \ sourceOptions: #{
      \ _: #{
      \ matchers: [ 'matcher_substring' ],
      \ },
      \ source: #{
      \ defaultAction: 'execute'
      \ }
      \ },
      \ kindOptions: #{
      \ file: #{
      \ defaultAction: 'open',
      \ },
      \ },
      \ })
```

Please test the config.

I have tested:

`Ddu file`
`call ddu#ui#sync_action('quit')`
`Ddu file` again

**Comment by mikelue** [comment]
I'll try to use clean environment to see if I can eliminate the issue.
I appreciate your time.

**Comment by Shougo** [comment]
I need to check textlock state.  But I don't know why the error is occurred.

**Comment by Shougo** [comment]
I have added the error check.

**Comment by mikelue** [comment]
I miss an operation for the of error message, use `j` or `k` to move the cursor, then close list of DDU.
After that, re-opening DDU list would get me the error message.

I apologize.

**Comment by Shougo** [comment]
Sorry.  I don't reproduce the error.

**Comment by Shougo** [comment]
I don't work for the non reproduce-able issue.
But I have added `force` flag in quit action.  You can use it.

**Comment by Shougo** [comment]
Other plugins or configuration may be affected.  But I don't know.

**Comment by mikelue** [comment]
I will update this issue if I can figure out any cause for this issue.
Thanks a lot.
