### ISSUE TITLE
Error when closing filter window

### ISSUE THREAD

**Issue by hyuoou** [Shougo/ddu-ui-ff#56]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
An error occurs when I try to close the filter window with autoAction and startFilter set.

## Expected
Close filter window without error.

## Environment Information

- ddu-ui-ff version (SHA1): `ba8be0062bd67d5f4a93933600e66ece30a812cd`

- denops.vim version (SHA1): `d7db28587bb281f9fcf56d4986e313025e250295`

- deno version(`deno -V` output): `deno 1.26.0`

- OS: `Arch Linux`

- neovim/Vim `:version` output:
```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

      システム vimrc: "$VIM/sysinit.vim"
       省略時の $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)
```vim
set runtimepath^=~/plugins/denops.vim
set runtimepath^=~/plugins/ddu.vim
set runtimepath^=~/plugins/ddu-ui-ff
set runtimepath^=~/plugins/ddu-source-file_rec
set runtimepath^=~/plugins/ddu-filter-matcher_substring
set runtimepath^=~/plugins/ddu-kind-file

call ddu#custom#patch_global({
  \ 'ui': 'ff',
  \ 'uiParams': {
  \   'ff': {
  \     'split': 'floating',
  \     'startFilter': v:true,
  \     'autoAction': {'name': 'preview'},
  \   },
  \ },
  \ 'sources': [{'name': 'file_rec', 'params': {}}],
  \ 'sourceOptions': {
  \   '_': {
  \     'matchers': ['matcher_substring'],
  \   },
  \ },
  \ 'kindOptions': {
  \   'file': {
  \     'defaultAction': 'open',
  \   },
  \ }
  \ })

autocmd FileType ddu-ff call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer><silent> <CR> <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  nnoremap <buffer><silent> i <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
  nnoremap <buffer><silent> q <Cmd>call ddu#ui#ff#do_action('quit')<CR>
endfunction

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  inoremap <buffer><silent> <CR> <Esc><Cmd>close<CR>
  nnoremap <buffer><silent> <CR> <Esc><Cmd>close<CR>
endfunction
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Execute `call ddu#start({})`
2. Close filter window.

## Screenshot (if possible)
![error](https://user-images.githubusercontent.com/63180765/193396238-327be0be-9c15-44d0-aca2-05c7e52edea5.png)

## Upload the log messages by `:redir` and `:message` (if errored)
```
CursorMoved Autocommands for "<buffer=2>"..function ddu#ui#ff#_do_auto_action[13]..ddu#ui#ff#do_action[13]..ddu#ui_action[1]..ddu#_request[22]..denops#request[1]..denops#server#request[6]..<SNR>17_request の処理中にエラーが検出されました:
行    1:
Error invoking 'invoke' on channel 4:
Error: Failed to call 'uiAction' with ["default","preview",{}]: Error: Failed to call 'call' with ["ddu#ui#ff#_open_preview_window",{"autoAction":{"name":"preview","params":{}},"autoResize":false,"cursorPos":-1,"displaySourceName":"no","filterFloatingPosition":"bottom","filterSplitDirection":"botright","filterUpdateTime":0,"floatingBorder":"none","highlights":{},"ignoreEmpty":false,"previewCol":0,"previewFloating":false,"previewHeight":10,"previewRow":0,"previewVertical":false,"previewWidth":40,"previewFloatingBorder":"none","previewFloatingZindex":50,"prompt":"","reversed":false,"split":"floating","splitDirection":"botright","startFilter":true,"statusline":true,"winCol":0,"winHeight":20,"winRow":0,"winWidth":0},2]: Error: Failed to call 'nvim_call_function' with ["ddu#ui#ff#_open_preview_window",[{"autoAction":{"name":"preview","params":{}},"autoResize":false,"cursorPos":-1,"displaySourceName":"no","filterFloatingPosition":"bottom","filterSplitDirection":"botright","filterUpdateTime":0,"floatingBorder":"none","highlights":{},"ignoreEmpty":false,"previewCol":0,"previewFloating":false,"previewHeight":10,"previewRow":0,"previewVertical":false,"previewWidth":40,"previewFloatingBorder":"none","previewFloatingZindex":50,"prompt":"","reversed":false,"split":"floating","splitDirection":"botright","startFilter":true,"statusline":true,"winCol":0,"winHeight":20,"winRow":0,"winWidth":0},2]]: [0,"Vim(new):E242: Can't split a window while closing another"]
    at Session.call (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:207:13)
    at async Service.call (file:///home/hyuoou/plugins/denops.vim/denops/@denops-private/service.ts:99:12)
    at async Session.call (file:///home/hyuoou/plugins/denops.vim/denops/@denops-private/service.ts:166:14)
    at async Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:99:12)
    at async https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:108:18
    at async Session.handleRequest (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:104:29)
    at Session.call (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:207:13)
    at async DenopsImpl.call (file:///home/hyuoou/plugins/denops.vim/denops/@denops/impl.ts:34:12)
    at async PreviewUi.previewBuffer (file:///home/hyuoou/plugins/ddu-ui-ff/denops/@ddu-ui-ff/preview.ts:194:7)
    at async PreviewUi.preview (file:///home/hyuoou/plugins/ddu-ui-ff/denops/@ddu-ui-ff/preview.ts:106:14)
    at async Ddu.uiAction (file:///home/hyuoou/plugins/ddu.vim/denops/ddu/ddu.ts:543:19)
    at async Session.uiAction (file:///home/hyuoou/plugins/ddu.vim/denops/ddu/app.ts:233:7)
    at async Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:99:12)
    at async https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:108:18
    at async Session.handleRequest (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:104:29)
    at Session.call (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:207:13)
    at async Service.dispatch (file:///home/hyuoou/plugins/denops.vim/denops/@denops-private/service.ts:114:14)
    at async Session.invoke (file:///home/hyuoou/plugins/denops.vim/denops/@denops-private/host/nvim.ts:53:16)
    at async Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:99:12)
    at async https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:108:18
    at async Session.handleRequest (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:104:29)
```

**Comment by 4513ECHO** [comment]
You should use `ddu#ui#ff#close()` instead of `:close` in mappings.

**Comment by hyuoou** [comment]
The same problem occurred when using `ddu#ui#ff#close()`.

**Comment by hyuoou** [comment]
The same problem occurs when using `ddu#ui#ff#close()`.

```vim
set runtimepath^=~/plugins/denops.vim
set runtimepath^=~/plugins/ddu.vim
set runtimepath^=~/plugins/ddu-ui-ff
set runtimepath^=~/plugins/ddu-source-file_rec
set runtimepath^=~/plugins/ddu-filter-matcher_substring
set runtimepath^=~/plugins/ddu-kind-file

call ddu#custom#patch_global({
  \ 'ui': 'ff',
  \ 'uiParams': {
  \   'ff': {
  \     'split': 'floating',
  \     'startFilter': v:true,
  \     'autoAction': {'name': 'preview'},
  \   },
  \ },
  \ 'sources': [{'name': 'file_rec', 'params': {}}],
  \ 'sourceOptions': {
  \   '_': {
  \     'matchers': ['matcher_substring'],
  \   },
  \ },
  \ 'kindOptions': {
  \   'file': {
  \     'defaultAction': 'open',
  \   },
  \ }
  \ })

autocmd FileType ddu-ff call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer><silent> <CR> <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  nnoremap <buffer><silent> i <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
  nnoremap <buffer><silent> q <Cmd>call ddu#ui#ff#do_action('quit')<CR>
endfunction

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  inoremap <buffer><silent> <CR> <Esc><Cmd>call ddu#ui#ff#close()<CR>
  nnoremap <buffer><silent> <CR> <Cmd>call ddu#ui#ff#close()<CR>
endfunction
```

**Comment by Shougo** [comment]
Fixed.
