### ISSUE TITLE
Text property error (E275) when close FF window immediately

### ISSUE THREAD

**Issue by Milly** [Shougo/ddu-ui-ff#60]
# Problems summary

If user immediately closes the FF window, get a text property error (E275).

## Expected

Close FF window without error.

## Environment Information

- ddu-ui-ff version (SHA1): 7a18cfc 

- denops.vim version (SHA1): vim-denops/denops.vim@3c3a0f9

- ddu.vim version (SHA1): Shougo/ddu.vim@fdc1ac7

- deno version(`deno -V` output): `deno 1.28.2`

- OS: Windows 10 22H2 (19045.2251)

- neovim/Vim `:version` output:
```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov 22 2022 23:29:02)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-924
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
" vimrc
set nocompatible

set rtp^=~/path/to/denops.vim
set rtp^=~/path/to/ddu.vim
set rtp^=~/path/to/ddu-ui-ff

call ddu#custom#patch_global(#{
\ ui: 'ff',
\ sources: [ #{ name: 'testsource', params: {} } ],
\})

nnoremap gy <Cmd>call ddu#start({})<CR>
autocmd FileType ddu-ff
      \ nnoremap <buffer> q <Cmd>call ddu#ui#ff#do_action('quit')<CR>

" testing
" 1. Start ddu.
  autocmd User DenopsPluginPost:ddu call timer_start(1000, {-> feedkeys('gy')})
" 2. Quit ddu-ff immediately.
  autocmd FileType ddu-ff call timer_start(100, {-> feedkeys('q')})
```

Test source that returns `Item.highlights`.

```typescript
// denops/@ddu-sources/testsource
import { delay } from "https://deno.land/std@0.166.0/async/delay.ts";
import { BaseSource } from "https://deno.land/x/ddu_vim@v2.0.0/types.ts";
import type { Item } from "https://deno.land/x/ddu_vim@v2.0.0/types.ts";

type Params = Record<never, never>;

export type ActionData = {
  text: string;
};

export class Source extends BaseSource<Params> {
  override kind = "word";

  override gather(): ReadableStream<Item<ActionData>[]> {
    return new ReadableStream({
      async start(controller) {
        const items: Item<ActionData>[] = [
          {
            word: "a:foo",
            action: {
              text: "foo",
            },
            highlights: [
              {
                name: "header",
                hl_group: "ErrorMsg",
                col: 1,
                width: 2,
              },
            ],
          },
        ];

        controller.enqueue(items);
        controller.close();
      },
    });
  }

  override params(): Params {
    return {};
  }
}
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Run `vim -u vimrc`.
2. Wait 1 second (test running).

## Upload the log messages by `:redir` and `:message` (if errored)

```
[ddu] ui: ff "redraw()" failed
[ddu] Failed to call 'call' with ["ddu#ui#ff#_highlight_items",{"autoAction":{},"autoResize":false,"cursorPos":-1,"displaySourceName":"no","displayTree":false,"filterFloatingPosition":"bottom","filterSplitDirection":"botright","filterUpdateTime":0,"floatingBorder":"none","highlights":{},"ignoreEmpty":false,"previewCol":0,"previewFloating":false,"previewFloatingBorder":"none","previewFloatingZindex":50,"previewHeight":10,"previewRow":0,"previewVertical":false,"previewWidth":40,"prompt":"","reversed":false,"replaceCol":0,"split":"horizontal","splitDirection":"botright","startFilter":false,"statusline":true,"winCol":20,"winHeight":20,"winRow":2,"winWidth":40},2,1,[{"highlights":[{"name":"header","hl_group":"ErrorMsg","col":1,"width":2}],"row":1,"prefix":""}],[]]: Error: Failed to call 'ddu#ui#ff#_highlight_items([object Object], 2, 1, [object Object], )': Vim(call):E275: Cannot add text property to unloaded buffer
function ddu#ui#ff#do_action[13]..ddu#ui_action[1]..ddu#_request[22]..denops#request[1]..denops#server#request[6]..<SNR>23_request[1]..denops#api#vim#call[2]..ddu#ui#ff#_highlight_items[12]..ddu#ui#ff#_highlight, line 22
    at Vim.call (file:///tmp/denops.vim/denops/@denops-private/host/vim.ts:37:13)
    at async Session.call (file:///tmp/denops.vim/denops/@denops-private/service.ts:170:14)
    at async Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:99:12)
    at async https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:108:18
    at async Session.handleRequest (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:104:29)
[ddu] Error: Failed to call 'call' with ["ddu#ui#ff#_highlight_items",{"autoAction":{},"autoResize":false,"cursorPos":-1,"displaySourceName":"no","displayTree":false,"filterFloatingPosition":"bottom","filterSplitDirection":"botright","filterUpdateTime":0,"floatingBorder":"none","highlights":{},"ignoreEmpty":false,"previewCol":0,"previewFloating":false,"previewFloatingBorder":"none","previewFloatingZindex":50,"previewHeight":10,"previewRow":0,"previewVertical":false,"previewWidth":40,"prompt":"","reversed":false,"replaceCol":0,"split":"horizontal","splitDirection":"botright","startFilter":false,"statusline":true,"winCol":20,"winHeight":20,"winRow":2,"winWidth":40},2,1,[{"highlights":[{"name":"header","hl_group":"ErrorMsg","col":1,"width":2}],"row":1,"prefix":""}],[]]: Error: Failed to call 'ddu#ui#ff#_highlight_items([object Object], 2, 1, [object Object], )': Vim(call):E275: Cannot add text property to unloaded buffer
function ddu#ui#ff#do_action[13]..ddu#ui_action[1]..ddu#_request[22]..denops#request[1]..denops#server#request[6]..<SNR>23_request[1]..denops#api#vim#call[2]..ddu#ui#ff#_highlight_items[12]..ddu#ui#ff#_highlight, line 22
    at Vim.call (file:///tmp/denops.vim/denops/@denops-private/host/vim.ts:37:13)
    at async Session.call (file:///tmp/denops.vim/denops/@denops-private/service.ts:170:14)
    at async Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:99:12)
    at async https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:108:18
    at async Session.handleRequest (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:104:29)
    at Session.call (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:207:13)
    at async DenopsImpl.call (file:///tmp/denops.vim/denops/@denops/impl.ts:34:12)
    at async Ui.redraw (file:///C:/tmp/ddu-ui-ff/denops/@ddu-uis/ff.ts:350:5)
    at async file:///tmp/ddu.vim/denops/ddu/ddu.ts:1501:7
    at async Lock.with (https://deno.land/x/async@v1.1.5/lock.ts:23:7)
    at async uiRedraw (file:///tmp/ddu.vim/denops/ddu/ddu.ts:1499:3)
    at async Ddu.uiRedraw (file:///tmp/ddu.vim/denops/ddu/ddu.ts:458:5)
    at async Ddu.redraw (file:///tmp/ddu.vim/denops/ddu/ddu.ts:408:5)
    at async readChunk (file:///tmp/ddu.vim/denops/ddu/ddu.ts:366:9)
```

**Comment by Shougo** [comment]
Fixed.
